Repository turbomates/kotlin-back-sdk, pull requests merged in 2022-01, with the labels that each got.

#33 Fix query converter
  build.gradle.kts
  src/main/kotlin/dev/tmsoft/lib/filter/QueryConverter.kt
  src/test/kotlin/dev/tmsoft/lib/filter/QueryConverterTest.kt
Labels: backend, bug

#34 Adding Vault client
  build.gradle.kts
  src/main/kotlin/dev/tmsoft/lib/vault/VaultAPI.kt
  src/main/kotlin/dev/tmsoft/lib/vault/VaultHoplitePreprocessor.kt
Labels: backend

#35 Sorting Params
  .github/workflows/publish.yml
  .github/workflows/test.yml
  build.gradle.kts
  src/main/kotlin/dev/tmsoft/lib/exposed/query/QueryExecutor.kt
  src/main/kotlin/dev/tmsoft/lib/exposed/query/QueryFold.kt
  src/main/kotlin/dev/tmsoft/lib/exposed/query/QueryObject.kt
  src/main/kotlin/dev/tmsoft/lib/filter/InvalidValue.kt
  src/main/kotlin/dev/tmsoft/lib/ktor/Response.kt
  src/main/kotlin/dev/tmsoft/lib/openapi/OpenAPI.kt
  src/main/kotlin/dev/tmsoft/lib/openapi/ktor/OpenAPI.kt
  src/main/kotlin/dev/tmsoft/lib/query/exceptions/InvalidValue.kt
  src/main/kotlin/dev/tmsoft/lib/query/exceptions/NotEnoughInformation.kt
  src/main/kotlin/dev/tmsoft/lib/query/filter/Field.kt
  src/main/kotlin/dev/tmsoft/lib/query/filter/Filter.kt
  src/main/kotlin/dev/tmsoft/lib/query/filter/PathValues.kt
  src/main/kotlin/dev/tmsoft/lib/query/filter/QueryConverter.kt
  src/main/kotlin/dev/tmsoft/lib/query/filter/Router.kt
  src/main/kotlin/dev/tmsoft/lib/query/filter/Value.kt
  src/main/kotlin/dev/tmsoft/lib/query/filter/type/DateTimeRange.kt
  src/main/kotlin/dev/tmsoft/lib/query/paging/ContinuousList.kt
  src/main/kotlin/dev/tmsoft/lib/query/paging/PagingParameters.kt
  src/main/kotlin/dev/tmsoft/lib/query/paging/SortingParameters.kt
  src/test/kotlin/dev/tmsoft/lib/exposed/QueryFoldTest.kt
  src/test/kotlin/dev/tmsoft/lib/query/QueryConverterTest.kt
  src/test/kotlin/dev/tmsoft/lib/query/filter/FilterTest.kt
  src/test/kotlin/dev/tmsoft/lib/query/sorting/SortingTest.kt
Labels: backend, enhancement
